// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

type (
	ValidateRequest struct {
		UserId int    `json:"user_id"`
		Token  string `json:"token"`
	}
	// Formal exchange type, please do not delete.
	ValidateResponse struct{}

	DeleteRequest struct {
		UserId int    `json:"user_id"`
		Token  string `json:"token"`
	}
	// Formal exchange type, please do not delete.
	DeleteResponse struct{}
)
