// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

import (
	"context"
	endpoint "github.com/go-kit/kit/endpoint"
	main "microgen/main"
)

func Endpoints(svc main.Service) EndpointsSet {
	return EndpointsSet{
		DeleteEndpoint:   DeleteEndpoint(svc),
		ValidateEndpoint: ValidateEndpoint(svc),
	}
}

func ValidateEndpoint(svc main.Service) endpoint.Endpoint {
	return func(arg0 context.Context, request interface{}) (interface{}, error) {
		req := request.(*ValidateRequest)
		res0 := svc.Validate(arg0, req.UserId, req.Token)
		return &ValidateResponse{}, res0
	}
}

func DeleteEndpoint(svc main.Service) endpoint.Endpoint {
	return func(arg0 context.Context, request interface{}) (interface{}, error) {
		req := request.(*DeleteRequest)
		res0 := svc.Delete(arg0, req.UserId, req.Token)
		return &DeleteResponse{}, res0
	}
}
