// Code generated by microgen 1.0.4. DO NOT EDIT.

package transporthttp

import (
	httpkit "github.com/go-kit/kit/transport/http"
	transport "microgen/main/transport"
	"net/url"
)

func NewHTTPClient(u *url.URL, opts ...httpkit.ClientOption) transport.EndpointsSet {
	return transport.EndpointsSet{
		DeleteEndpoint: httpkit.NewClient(
			"DELETE", u,
			_Encode_Delete_Request,
			_Decode_Delete_Response,
			opts...,
		).Endpoint(),
		ValidateEndpoint: httpkit.NewClient(
			"GET", u,
			_Encode_Validate_Request,
			_Decode_Validate_Response,
			opts...,
		).Endpoint(),
	}
}
