// Code generated by microgen 1.0.4. DO NOT EDIT.

package transporthttp

import (
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	transport "microgen/main/transport"
	http1 "net/http"
)

func NewHTTPHandler(endpoints *transport.EndpointsSet, opts ...http.ServerOption) http1.Handler {
	mux := mux.NewRouter()
	mux.Methods("GET").Path("/jrss/api/session/validate").Handler(
		http.NewServer(
			endpoints.ValidateEndpoint,
			_Decode_Validate_Request,
			_Encode_Validate_Response,
			opts...))
	mux.Methods("DELETE").Path("/jrss/api/session").Handler(
		http.NewServer(
			endpoints.DeleteEndpoint,
			_Decode_Delete_Request,
			_Encode_Delete_Response,
			opts...))
	return mux
}
